on:
    issues: 
        types: [opened, labeled]

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Read event file
          run: |
            # Read the contents of the event file
            cat $GITHUB_EVENT_PATH