name: Minio

on: 
  workflow_dispatch:
  push:
    branches:
      - main
      - 'feature/*'

        
jobs:
    testing:
      
        runs-on: ubuntu-latest
        steps:
        - name: Checkout Repository
          uses: actions/checkout@v4

        - name: Minio Deploy
          uses: mamal72/minio-perfect-deploy-action@main
          with:
                endpoint: https://76d6a95c-6d82-4800-a3ff-d574a90d1fc1-10-244-4-113-31178.papa.r.killercoda.com
                access_key: miniadmin
                secret_key: minioadmin
                bucket: 'testing'
                source_dir: 'kubernetes'
                target_dir: '/'    

